apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: finance-tracker
  labels:
    release: monitoring
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: finance-tracker
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
      scrapeTimeout: 10s
