apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: finance-tracker
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/varunapriya360/example.git
    targetRevision: main
    path: finance-tracker
    helm:
      valueFiles:
        - values.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
